### ISSUE TITLE
HMAC-SHA2 prefered over UMAC in OpenSSH 

### ISSUE THREAD

**Issue by azet** [RaymiiOrg/cipherli.st#27]
Hi,

Why is HMAC-SHA2 (512) preferred over the faster and more secure UMAC?

Thanks,
Aaron

**Comment by azet** [comment]
BTW the client configuration in general will make it impossible to connect to older OpenSSH releases (or any kind of networking gear for that matter).

**Comment by dvergeylen** [comment]
Having the same problem here :confused:
