### ISSUE TITLE
nginx/Apache SSL session settings

### ISSUE THREAD

**Issue by azet** [RaymiiOrg/cipherli.st#28]
Hi,

nginx and Apache do not seem to have a session cache timeout. They can also be optimized to use a buffer size of 1400 (fit in one MTU). Another thing is that session tickets are not disabled. With current builds session ticket keys never get rotated, this is a real security issue.

Thanks,
Aaron

**Comment by RaymiiOrg** [comment]
Is this fixable in config or does this require upstream fixing and users upgrading?

**Comment by azet** [comment]
There are a couple of solutions to this. The easierst one being to disable session tickets, that's possible for Apache and nginx:

http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_tickets
https://httpd.apache.org/docs/trunk/mod/mod_ssl.html

I'm not sure about lighty and could not find appropriate documentation.

The other solution is to regularly clean the ticket file and restart the webservers. Twitter recently published a callback API for OpenSSL to automate this, though this is not supported in upstream implementations yet: https://github.com/twitter/sslconfig/blob/master/patches/openssl_session_ticket.patch

**Comment by azet** [comment]
Session Cache Timeout and Buffer size can be similarly set by options in the configuration of the server daemon.
