### ISSUE TITLE
HPKP

### ISSUE THREAD

**Issue by azet** [RaymiiOrg/cipherli.st#29]
None of the webserver configurations set HPKP headers.

https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

**Comment by RaymiiOrg** [comment]
The background articles all describe HPKP. Not sure if it would fit graphically. Visitors should still be able to copy paste the settings, force them to generate an SPKI hash or remove that line would work counter-intuitively IMHo.

**Comment by azet** [comment]
I agree, but maybe it should be stated below the server configurations or automated via an accompanying script?

**Comment by RaymiiOrg** [comment]
Correct, added a suggestion.
