### ISSUE TITLE
Mailserver cipher settings result in plaintext fallback

### ISSUE THREAD

**Issue by azet** [RaymiiOrg/cipherli.st#31]
Hi,

Due to the strong cipher settings in the mailserver section a good portion of MTAs will fail to negotiate any ciphersuite, resulting in a plaintext fallback.

Aaron

**Comment by RaymiiOrg** [comment]
Please provide more information, example or documentation proving this.

**Comment by azet** [comment]
That's pretty straight forward: if two MTAs can't agree on a common ciphersuite the fallback is automatically to send with plaintext. This ciphersuite is specifically ECC + AES. If one of the participating servers does not support either of those, the mail will be sent in plain text. This is why a lot of (especially high traffic) mail services still offer RC4 and triple-DES.

This affects specifically exim to the best of my knowledge. With Postfix you can (and do) set mandatory ciphers, so if there's a TLS connection error (i.e. because no common ciphersuite could be negotiated) the mail is not sent at all.

**Comment by tcitworld** [comment]
@RaymiiOrg Can we have an update on this ?

**Comment by f-andrey** [comment]
I'm tried strong to implement cipher settings (without DES) cipher and cipher_server_preference for EXIM. For authorized to send mail clients, I had to turn back DES (some windows are too old clients). mx and rly servers can be run with  strong cipher settings (error rate is very low, it seems only the server spam)
