### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by davidjpeacock** [RaymiiOrg/cipherli.st#38]
Hey there,

Firstly, let me applaud your work on cipherli.st!  It's great to have a definitive resource; serious kudos is due to you.   Thank you for doing this. :-)

I'd like to suggest that you reformat the presentation so that line wrapping doesn't occur please?  It's quite awkward to read and this is of course syntax that should be ultra clear.  I'm attaching a screenshot of how it looks on my 13" screen incase you have a huge monitor and don't know what I'm talking about.

Thank you very much!

David

![cipherli st-ss](https://cloud.githubusercontent.com/assets/4322375/7748358/b5476b3e-ff91-11e4-9a8e-44a0b84fed62.png)

**Comment by RaymiiOrg** [comment]
That indeed looks a bit off. I'm using bootstrap, and on my 9" EEE book it just wraps the collums beneath each other. What happens when you smallen the window?

**Comment by davidjpeacock** [comment]
Interesting, when I make the window marginally smaller it makes the individual code windows fall in below each other, in a column, I think as you describe.  But yeah, past a point at my normal browser size, it does line wrapping as opposed to code-block aligning..
