### ISSUE TITLE
Site cannot be loaded in firefox

### ISSUE THREAD

**Issue by skibbipl** [RaymiiOrg/cipherli.st#39]
Hello,
I tried to access cipherli.st today with my firefox (developer edition 40.0a2 (2015-05-24)) and I got mozilla_pkix_error_key_pinning_failure error.
Site works fine in chrome - so I'm not sure if it's related to Firefox or site itself.

EDIT:
Recent firefox update loads site correctly.

Regards

**Comment by RaymiiOrg** [comment]
Thanks for the info. The certitifcate was replaced, but the pinning was done so 3 months ahead...
