### ISSUE TITLE
Certificate chain (https://cipherli.st)

### ISSUE THREAD

**Issue by anand-bhat** [RaymiiOrg/cipherli.st#40]
This is related to the website's setting and not the content.

Please consider serving the intermediate certificate with Fingerprint: ae223cbf20191b40d7ffb4ea5701b65fdc68a1ca in the chain (cert 3 in Trusted path 2 below). This will be useful for clients that do not have the ECC Cert Auth root certificate in their default CA store (e.g., Java 8). Serving this intermediate cert will complete a chain that's valid. [Related (but not the same issue)](http://stackoverflow.com/a/30490518/4483015).

Great website, by the way!

Also consider removing the root certificate with Fingerprint: 9f744e9f2b4dbaec0f312c50b6563b8e2d93c311 from being served (cert 3 in Trust path 1 below). If the root isn't in a client's trust store, serving it will not be of any use as trust will not be verified.

![image](https://cloud.githubusercontent.com/assets/7332442/7874682/fa86b84a-0580-11e5-999f-03c3d9310e7f.png)

**Comment by RaymiiOrg** [comment]
Better this way?

**Comment by anand-bhat** [comment]
Definitely! Although, as I seem to be picking nits today, you are now serving the AddTrust External CA Root certificate (Fingerprint: 02faf3e291435468607857694df5e45b68851868), that needn't be included. No harm really, only adds a needless overhead in the handshake.

I can confirm that a Java 8 based client can now access the site (was not reachable previously).

![image](https://cloud.githubusercontent.com/assets/7332442/7875559/fa86a9d4-058c-11e5-9918-46f014e7745b.png)

![image](https://cloud.githubusercontent.com/assets/7332442/7875578/08dc5150-058d-11e5-9362-5ffda2856079.png)

**Comment by RaymiiOrg** [comment]
What do you use to visits the site from a Java 8 client? (And out of interest, why?)

**Comment by anand-bhat** [comment]
For this particular case, I used a simple Java program similar to the one in the SO thread to connect to the site. Why? Just because I was curious to see if the COMODO ECC root was in the Java 8 cacerts. In general, I build Java based programs if I have a need to automate something resembling a lookup or a fetch (like a bot). Granted, there are better tools out there but the heart wants what it wants ;)
