### ISSUE TITLE
more strong chiper control for exim

### ISSUE THREAD

**Issue by f-andrey** [RaymiiOrg/cipherli.st#57]
https://bettercrypto.org/ have nice recommendation for more strong chiper control for exim.
Enable openssl_options = +no_sslv2 +no_sslv3 +no_compression +cipher_server_preference
This work fine and remove client side negotiation, but need more liberal  chiper for server if served by an unlimited range of customers see #31

**Comment by azet** [comment]
Hi,

We're currently working on integrating Postfix, Exim and other mailservers into Let's Encrypt (Certbot is the tool called that auto-configures stuff for you, now) within EFF. This project still has a long road ahead, and exim integration hasn't yet started, once we're done with that, you may want to switch to this. For now the best option in my opinion is still the bettercrypto recommended settings, these have been authored, revised and reviewed by people running large mail services and admins from universities with hundreds of thousands of students. So I think these are sound and safe for the time being.

Aaron

/cc @RaymiiOrg
