### ISSUE TITLE
Dovecot SSL configs stops Thunderbird from connecting

### ISSUE THREAD

**Issue by snassar** [RaymiiOrg/cipherli.st#58]
The SSL config for dovecot on Debian Jessie (2.2.13-12~deb8u1) stops Thunderbird 45 from connecting.

**Comment by RaymiiOrg** [comment]
Please provide a bit more information like dovecot error logging or thunderbird error logs

**Comment by mozkeeler** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1335346
It looks like the dovecot (and exim) configurations result in only supporting DHE-RSA-AES256-GCM-SHA384 and DHE-RSA-AES256-SHA256.

There may be others also enabled, but the long story short is it doesn't intersect with the list of cipher suites enabled by default in Firefox/Thunderbird, which can be found here: https://dxr.mozilla.org/mozilla-central/rev/1d025ac534a6333a8170a59a95a8a3673d4028ee/security/manager/ssl/nsNSSComponent.cpp#1315
