### ISSUE TITLE
https:cipherli.st fails HPKP validation

### ISSUE THREAD

**Issue by dr8** [RaymiiOrg/cipherli.st#59]
[Not technically an issue with the content of cipherli.st, but as it's a TLS issue, I thought it was worth asking about.]

I'm getting HPKP validation errors and blocked from accessing cipherli.st via chrome 52 on Android.
ssllabs.com and htbridge.com confirm the error (that no matching certificates are found).
[https://www.ssllabs.com/ssltest/analyze.html?d=cipherli.st&s=128.199.39.10](https://www.ssllabs.com/ssltest/analyze.html?d=cipherli.st&s=128.199.39.10)

However, Chrome 51 (on ChromeOS) is connecting; even though it refuses to connect (correctly) to the test page linked within: [https://projects.dm.id.lv/Public-Key-Pins_test](https://projects.dm.id.lv/Public-Key-Pins_test)

For what it's worth, the header that I am getting is:
`Public-Key-Pins: pin-sha256="AWFBG0p7ynqPzJBvz37wsEko4HY1X0TS24C5XOs91nw="; pin-sha256="EohwrK1N7rr3bRQphPj4j2cel+B2d0NNbM9PWHNDXpM="; max-age=2592000; includeSubDomains`

And the cert chain I'm getting (with SHA256 fingerprints as displayed by Chrome)  are:
**cipherli.st** (E6 03 60 D7 24 61 AD 47 54 4B 9D 69 27 D9 7E 61 29 B6 BC 71 6C 3E 7B 3D 3C F8 94 17 BA D4 2F 3E)
**Let's Encrypt Authority X3** (25 84 7D 66 8E B4 F0 4F DD 40 B1 2B 6B 07 40 C5 67 DA 7D 02 43 08 EB 6C 2C 96 FE 41 D9 DE 21 8D)
**DST Root CA X3** (06 87 26 03 31 A7 24 03 D9 09 F1 05 E6 9B CF 0D 32 E1 BD 24 93 FF C6 D9 20 6D 11 BC D6 77 07 39)

I am not an HPKP expert, but I'd like to understand it better. I would appreciate understanding what is happening here, for my own education, if nothing else.

**Comment by dr8** [comment]
I can see that you've updated your HPKP headers, but I'm still getting no match. I don't understand why I am able to connect, given the HPKP errors. Surely that is exactly what HPKP should protect against. Is there something that I'm missing?

Also, strangely my Android device is now connecting, even though it refused before; and though we're within the max age that you had specified yesterday (you had 2592000 seconds = 30 days).

Do you know why that is?



FWIW, the HPKP hashes that I would expect for the certs I'm seeing are:
```
cipherli.st: pin-sha256="ny3PTSkEFEPZQxSCw1Bw8AHg3B5iAa7tFBqRWw22QZg="
Let's Encrypt Authority X3: pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
DST Root CA X3: pin-sha256="Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys="
```

The values above were generated by hand and verified with this website: [https://report-uri.io/home/pkp_hash](https://report-uri.io/home/pkp_hash)

**Comment by dr8** [comment]
I now think that I'm getting closer to understanding this. 

1. HPKP doesn't apply on first visit. Only after you've visited a site over TLS with correct HPKP headers will HPKP validation apply (i.e. for subsequent visits).
2. In order for your HPKP headers to be valid, they **must** include a pin for a public key of a cert in your chain, (and they **must** include a pin for a public key that does not correspond to a cert in your chain - this is the backup key).
3. As your headers do not meet those criteria, they should NOT be cached (according to [https://tools.ietf.org/html/draft-ietf-websec-key-pinning-08#section-2.5](url)) and so shouldn't be used to check future visits (to prevent denial of service attacks using HPKP).


In Chrome, you can check the pinned key hashes in chrome://net-internals.

Chrome 51 on ChromeOS (Chrome Beta) shows no pinned values, and allows connections; which is correct.
Chrome 52 on Android (Chrome Dev) shows the pinned values as from your site yesterday (and is not allowing connections). Caching your headers **even though they are not valid** appears to be an error.

So my confusion over behaviour stems from a Chrome Dev bug, and my misunderstanding over HPKP not being applied on first visit.

Of course, you still need to fix your HPKP headers ;-)

**Comment by RaymiiOrg** [comment]
I like the way you research your stuff :+1: 

I did screw up the HPKP headers while moving to Let's Encrypt from a Comodo certificate. Sorry for that. Headers should be fixed now, I had to manually remove them from this file:

    ~/.mozilla/firefox/<profile.default>/SiteSecurityServiceState.txt

before my browser (firefox) would load the page again.

**Comment by dr8** [comment]
Thanks.
Not a Chrome bug then. I must have visited your site using Chrome 52 when the headers were valid (on the Comodo certificate), and it was therefore behaving as expected when I revisited and it found the headers were incorrect.

The other versions of Chrome were also behaving correctly, because they'd never seen a correct header.

Chrome is now caching the new headers, which seem to be correct, as you say, so order is restored :-)
