### ISSUE TITLE
up to date?

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [RaymiiOrg/cipherli.st#61]
are these ciphers still up to date? i was looking at https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility and realised that your list of ciphers is very small (not a bad thing) and was wondering if its still valid as the best ciphers possible

**Comment by natevw** [comment]
+1, I was wondering the same thing. I was thinking it would be helpful to at least have a "last updated" date visible on the site.

"Workaround" :-) is that I obviously did find the link to this repo (thanks @RaymiiOrg for including that!) so I can at least get that info via the commit logs here instead.

**Comment by RaymiiOrg** [comment]
Ciphers are still up to date and still give a very secure connection.

**Comment by berrythesoftwarecodeprogrammar** [comment]
thanks :)
