### ISSUE TITLE
Postfix Apple Mail

### ISSUE THREAD

**Issue by PHP-Expert** [RaymiiOrg/cipherli.st#68]
Apple Mail and iOS Mail only supports TLSV1 as most secure smtp Connection TLSV1.2 is not yet implemented.

**Comment by mkzero** [comment]
Sorry, but I kinda don't see a reason to change something for a broken system that will get a fix(and thus PCI-compliance) with the next version..?

**Comment by PHP-Expert** [comment]
Could you write a hint, for those who still use or have customers with Apple OS?

**Comment by strugee** [comment]
@PHP-Expert if I were you (assuming this is still an issue) I'd just use the intermediate profile of https://mozilla.github.io/server-side-tls/
