### ISSUE TITLE
Why no ChaCha in webserver cipherlists?

### ISSUE THREAD

**Issue by zofrex** [RaymiiOrg/cipherli.st#78]
My understanding (quite possibly wrong!) is that ChaCha20/Poly1305 is faster for mobile clients and still secure enough to use. How come it's not included in the webserver cipherlists? If there is a reason to not include it I think it would be great to document it :)

**Comment by concatime** [comment]
Token from the comments of this [post.](https://blog.cloudflare.com/do-the-chacha-better-mobile-performance-with-cryptography)
> Given now ARMv8 supports AES instructions, AES GCM is much faster on such phones than chaca_poly, according to Adam Langley on twitter

**Comment by concatime** [comment]
But I added ChaCha20 in my configuration.
> ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305 DHE-RSA-CHACHA20-POLY1305
