### ISSUE TITLE
Don't include 'preload' for HSTS header

### ISSUE THREAD

**Issue by ngyikp** [RaymiiOrg/cipherli.st#84]
https://hstspreload.org/#opt-in

In fact, cipherli.st was mentioned 2 times at the HSTS preload list removal bug: https://bugs.chromium.org/p/chromium/issues/detail?id=527947

**Comment by RaymiiOrg** [comment]
In the bug it says:

> Also, when I enabled preload, I did not actually know what I am doing,
> I was just following the recommendation from https://cipherli.st/.

This site is pretty clear in stating that you must at least understand what you're working on. User error IMHO.

**Comment by kkurian** [comment]
@RaymiiOrg To further avoid confusion, on the homepage, which warns "subdomains unavailable for a long, long time (see HSTS)" include not just a link to the Wikipedia article on HSTS but also to the deployment recommendations at https://hstspreload.org/#deployment-recommendations.
